import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
       <Head>
    <title>SplitIT</title>
      <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Navbar />

      <main >
        <div className='flex justify-center items-center my-14'>
          <div className='rounded-2xl bg-slate-700 '>
            <div className=' text-5xl text-gradient-to-r from-purple-500 to-pink-500 cursor-pointer  transition ease-in-out delay-50 hover:-translate-y-2 rounded-3xl font-bold my-4 mx-10'>
              Create A Room

            </div>

          </div>

        </div>

      </main>

    
    </div>
  )
}
